// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Cuemby.Equinix
{
    public static class GetMetalGateway
    {
        /// <summary>
        /// Use this datasource to retrieve Metal Gateway resources in Equinix Metal.
        /// 
        /// &gt; VRF features are not generally available. The interfaces related to VRF resources may change ahead of general availability.
        /// 
        /// {{% examples %}}
        /// ## Example Usage
        /// {{% example %}}
        /// 
        /// ```csharp
        /// using Pulumi;
        /// using Equinix = Cuemby.Equinix;
        /// using Equinix = Pulumi.Equinix;
        /// 
        /// class MyStack : Stack
        /// {
        ///     public MyStack()
        ///     {
        ///         // Create Metal Gateway for a VLAN with a private IPv4 block with 8 IP addresses
        ///         var testMetalVlan = new Equinix.MetalVlan("testMetalVlan", new Equinix.MetalVlanArgs
        ///         {
        ///             Description = "test VLAN in SV",
        ///             Metro = "sv",
        ///             ProjectId = local.Project_id,
        ///         });
        ///         var testGetMetalGateway = Output.Create(Equinix.GetMetalGateway.InvokeAsync(new Equinix.GetMetalGatewayArgs
        ///         {
        ///             GatewayId = local.Gateway_id,
        ///         }));
        ///     }
        /// 
        /// }
        /// ```
        /// {{% /example %}}
        /// {{% /examples %}}
        /// </summary>
        public static Task<GetMetalGatewayResult> InvokeAsync(GetMetalGatewayArgs args, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.InvokeAsync<GetMetalGatewayResult>("equinix:index/getMetalGateway:GetMetalGateway", args ?? new GetMetalGatewayArgs(), options.WithDefaults());

        /// <summary>
        /// Use this datasource to retrieve Metal Gateway resources in Equinix Metal.
        /// 
        /// &gt; VRF features are not generally available. The interfaces related to VRF resources may change ahead of general availability.
        /// 
        /// {{% examples %}}
        /// ## Example Usage
        /// {{% example %}}
        /// 
        /// ```csharp
        /// using Pulumi;
        /// using Equinix = Cuemby.Equinix;
        /// using Equinix = Pulumi.Equinix;
        /// 
        /// class MyStack : Stack
        /// {
        ///     public MyStack()
        ///     {
        ///         // Create Metal Gateway for a VLAN with a private IPv4 block with 8 IP addresses
        ///         var testMetalVlan = new Equinix.MetalVlan("testMetalVlan", new Equinix.MetalVlanArgs
        ///         {
        ///             Description = "test VLAN in SV",
        ///             Metro = "sv",
        ///             ProjectId = local.Project_id,
        ///         });
        ///         var testGetMetalGateway = Output.Create(Equinix.GetMetalGateway.InvokeAsync(new Equinix.GetMetalGatewayArgs
        ///         {
        ///             GatewayId = local.Gateway_id,
        ///         }));
        ///     }
        /// 
        /// }
        /// ```
        /// {{% /example %}}
        /// {{% /examples %}}
        /// </summary>
        public static Output<GetMetalGatewayResult> Invoke(GetMetalGatewayInvokeArgs args, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.Invoke<GetMetalGatewayResult>("equinix:index/getMetalGateway:GetMetalGateway", args ?? new GetMetalGatewayInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetMetalGatewayArgs : Pulumi.InvokeArgs
    {
        /// <summary>
        /// UUID of the metal gateway resource to retrieve.
        /// </summary>
        [Input("gatewayId", required: true)]
        public string GatewayId { get; set; } = null!;

        public GetMetalGatewayArgs()
        {
        }
    }

    public sealed class GetMetalGatewayInvokeArgs : Pulumi.InvokeArgs
    {
        /// <summary>
        /// UUID of the metal gateway resource to retrieve.
        /// </summary>
        [Input("gatewayId", required: true)]
        public Input<string> GatewayId { get; set; } = null!;

        public GetMetalGatewayInvokeArgs()
        {
        }
    }


    [OutputType]
    public sealed class GetMetalGatewayResult
    {
        public readonly string GatewayId;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// UUID of IP reservation block bound to the gateway.
        /// </summary>
        public readonly string IpReservationId;
        /// <summary>
        /// Size of the private IPv4 subnet bound to this metal gateway. One of
        /// `8`, `16`, `32`, `64`, `128`.
        /// </summary>
        public readonly int PrivateIpv4SubnetSize;
        /// <summary>
        /// UUID of the project where the gateway is scoped to.
        /// </summary>
        public readonly string ProjectId;
        /// <summary>
        /// Status of the gateway resource.
        /// </summary>
        public readonly string State;
        /// <summary>
        /// UUID of the VLAN where the gateway is scoped to.
        /// </summary>
        public readonly string VlanId;
        /// <summary>
        /// UUID of the VRF associated with the IP Reservation.
        /// </summary>
        public readonly string VrfId;

        [OutputConstructor]
        private GetMetalGatewayResult(
            string gatewayId,

            string id,

            string ipReservationId,

            int privateIpv4SubnetSize,

            string projectId,

            string state,

            string vlanId,

            string vrfId)
        {
            GatewayId = gatewayId;
            Id = id;
            IpReservationId = ipReservationId;
            PrivateIpv4SubnetSize = privateIpv4SubnetSize;
            ProjectId = projectId;
            State = state;
            VlanId = vlanId;
            VrfId = vrfId;
        }
    }
}
