// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Cuemby.Equinix
{
    /// <summary>
    /// Use this resource to create Metal User API Key resources in Equinix Metal. Each API key contains a
    /// token which can be used for authentication in Equinix Metal HTTP API (in HTTP request header
    /// `X-Auth-Token`).
    /// 
    /// Read-only keys only allow to list and view existing resources, read-write keys can also be used to
    /// create resources.
    /// 
    /// ## Example Usage
    /// 
    /// ```csharp
    /// using Pulumi;
    /// using Equinix = Cuemby.Equinix;
    /// 
    /// class MyStack : Stack
    /// {
    ///     public MyStack()
    ///     {
    ///         var test = new Equinix.MetalUserAPIKey("test", new Equinix.MetalUserAPIKeyArgs
    ///         {
    ///             Description = "Read-only user key",
    ///             ReadOnly = true,
    ///         });
    ///     }
    /// 
    /// }
    /// ```
    /// </summary>
    [EquinixResourceType("equinix:index/metalUserAPIKey:MetalUserAPIKey")]
    public partial class MetalUserAPIKey : Pulumi.CustomResource
    {
        /// <summary>
        /// Description string for the User API Key resource.
        /// * `read-only` - (Required) Flag indicating whether the API key shoud be read-only.
        /// </summary>
        [Output("description")]
        public Output<string> Description { get; private set; } = null!;

        /// <summary>
        /// Flag indicating whether the API key shoud be read-only
        /// </summary>
        [Output("readOnly")]
        public Output<bool> ReadOnly { get; private set; } = null!;

        /// <summary>
        /// API token which can be used in Equinix Metal API clients.
        /// </summary>
        [Output("token")]
        public Output<string> Token { get; private set; } = null!;

        /// <summary>
        /// UUID of the owner of the API key.
        /// </summary>
        [Output("userId")]
        public Output<string> UserId { get; private set; } = null!;


        /// <summary>
        /// Create a MetalUserAPIKey resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public MetalUserAPIKey(string name, MetalUserAPIKeyArgs args, CustomResourceOptions? options = null)
            : base("equinix:index/metalUserAPIKey:MetalUserAPIKey", name, args ?? new MetalUserAPIKeyArgs(), MakeResourceOptions(options, ""))
        {
        }

        private MetalUserAPIKey(string name, Input<string> id, MetalUserAPIKeyState? state = null, CustomResourceOptions? options = null)
            : base("equinix:index/metalUserAPIKey:MetalUserAPIKey", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/cuemby",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing MetalUserAPIKey resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static MetalUserAPIKey Get(string name, Input<string> id, MetalUserAPIKeyState? state = null, CustomResourceOptions? options = null)
        {
            return new MetalUserAPIKey(name, id, state, options);
        }
    }

    public sealed class MetalUserAPIKeyArgs : Pulumi.ResourceArgs
    {
        /// <summary>
        /// Description string for the User API Key resource.
        /// * `read-only` - (Required) Flag indicating whether the API key shoud be read-only.
        /// </summary>
        [Input("description", required: true)]
        public Input<string> Description { get; set; } = null!;

        /// <summary>
        /// Flag indicating whether the API key shoud be read-only
        /// </summary>
        [Input("readOnly", required: true)]
        public Input<bool> ReadOnly { get; set; } = null!;

        public MetalUserAPIKeyArgs()
        {
        }
    }

    public sealed class MetalUserAPIKeyState : Pulumi.ResourceArgs
    {
        /// <summary>
        /// Description string for the User API Key resource.
        /// * `read-only` - (Required) Flag indicating whether the API key shoud be read-only.
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// Flag indicating whether the API key shoud be read-only
        /// </summary>
        [Input("readOnly")]
        public Input<bool>? ReadOnly { get; set; }

        /// <summary>
        /// API token which can be used in Equinix Metal API clients.
        /// </summary>
        [Input("token")]
        public Input<string>? Token { get; set; }

        /// <summary>
        /// UUID of the owner of the API key.
        /// </summary>
        [Input("userId")]
        public Input<string>? UserId { get; set; }

        public MetalUserAPIKeyState()
        {
        }
    }
}
