// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Cuemby.Equinix
{
    /// <summary>
    /// Resource `equinix.NetworkSSHKey` allows creation and management of Equinix Network Edge SSH keys.
    /// 
    /// ## Import
    /// 
    /// This resource can be imported using an existing ID
    /// 
    /// ```sh
    ///  $ pulumi import equinix:index/networkSSHKey:NetworkSSHKey example {existing_id}
    /// ```
    /// </summary>
    [EquinixResourceType("equinix:index/networkSSHKey:NetworkSSHKey")]
    public partial class NetworkSSHKey : Pulumi.CustomResource
    {
        /// <summary>
        /// The name of SSH key used for identification.
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// The SSH public key. If this is a file, it can be read using the file
        /// interpolation function.
        /// </summary>
        [Output("publicKey")]
        public Output<string> PublicKey { get; private set; } = null!;

        /// <summary>
        /// The unique identifier of the key
        /// </summary>
        [Output("uuid")]
        public Output<string> Uuid { get; private set; } = null!;


        /// <summary>
        /// Create a NetworkSSHKey resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public NetworkSSHKey(string name, NetworkSSHKeyArgs args, CustomResourceOptions? options = null)
            : base("equinix:index/networkSSHKey:NetworkSSHKey", name, args ?? new NetworkSSHKeyArgs(), MakeResourceOptions(options, ""))
        {
        }

        private NetworkSSHKey(string name, Input<string> id, NetworkSSHKeyState? state = null, CustomResourceOptions? options = null)
            : base("equinix:index/networkSSHKey:NetworkSSHKey", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "https://github.com/cuemby/pulumi-equinix/releases/downloads/v${VERSION}",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing NetworkSSHKey resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static NetworkSSHKey Get(string name, Input<string> id, NetworkSSHKeyState? state = null, CustomResourceOptions? options = null)
        {
            return new NetworkSSHKey(name, id, state, options);
        }
    }

    public sealed class NetworkSSHKeyArgs : Pulumi.ResourceArgs
    {
        /// <summary>
        /// The name of SSH key used for identification.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// The SSH public key. If this is a file, it can be read using the file
        /// interpolation function.
        /// </summary>
        [Input("publicKey", required: true)]
        public Input<string> PublicKey { get; set; } = null!;

        public NetworkSSHKeyArgs()
        {
        }
    }

    public sealed class NetworkSSHKeyState : Pulumi.ResourceArgs
    {
        /// <summary>
        /// The name of SSH key used for identification.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// The SSH public key. If this is a file, it can be read using the file
        /// interpolation function.
        /// </summary>
        [Input("publicKey")]
        public Input<string>? PublicKey { get; set; }

        /// <summary>
        /// The unique identifier of the key
        /// </summary>
        [Input("uuid")]
        public Input<string>? Uuid { get; set; }

        public NetworkSSHKeyState()
        {
        }
    }
}
