// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package equinix

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetMetalPlans(ctx *pulumi.Context, args *GetMetalPlansArgs, opts ...pulumi.InvokeOption) (*GetMetalPlansResult, error) {
	var rv GetMetalPlansResult
	err := ctx.Invoke("equinix:index/getMetalPlans:GetMetalPlans", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking GetMetalPlans.
type GetMetalPlansArgs struct {
	// One or more attribute/values pairs to filter off of
	Filters []GetMetalPlansFilter `pulumi:"filters"`
	// One or more attribute/direction pairs on which to sort results. If multiple
	// sorts are provided, they will be applied in order
	Sorts []GetMetalPlansSort `pulumi:"sorts"`
}

// A collection of values returned by GetMetalPlans.
type GetMetalPlansResult struct {
	Filters []GetMetalPlansFilter `pulumi:"filters"`
	// The provider-assigned unique ID for this managed resource.
	Id string `pulumi:"id"`
	// The ID of the facility
	Plans []GetMetalPlansPlan `pulumi:"plans"`
	Sorts []GetMetalPlansSort `pulumi:"sorts"`
}

func GetMetalPlansOutput(ctx *pulumi.Context, args GetMetalPlansOutputArgs, opts ...pulumi.InvokeOption) GetMetalPlansResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (GetMetalPlansResult, error) {
			args := v.(GetMetalPlansArgs)
			r, err := GetMetalPlans(ctx, &args, opts...)
			var s GetMetalPlansResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(GetMetalPlansResultOutput)
}

// A collection of arguments for invoking GetMetalPlans.
type GetMetalPlansOutputArgs struct {
	// One or more attribute/values pairs to filter off of
	Filters GetMetalPlansFilterArrayInput `pulumi:"filters"`
	// One or more attribute/direction pairs on which to sort results. If multiple
	// sorts are provided, they will be applied in order
	Sorts GetMetalPlansSortArrayInput `pulumi:"sorts"`
}

func (GetMetalPlansOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetMetalPlansArgs)(nil)).Elem()
}

// A collection of values returned by GetMetalPlans.
type GetMetalPlansResultOutput struct{ *pulumi.OutputState }

func (GetMetalPlansResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetMetalPlansResult)(nil)).Elem()
}

func (o GetMetalPlansResultOutput) ToGetMetalPlansResultOutput() GetMetalPlansResultOutput {
	return o
}

func (o GetMetalPlansResultOutput) ToGetMetalPlansResultOutputWithContext(ctx context.Context) GetMetalPlansResultOutput {
	return o
}

func (o GetMetalPlansResultOutput) Filters() GetMetalPlansFilterArrayOutput {
	return o.ApplyT(func(v GetMetalPlansResult) []GetMetalPlansFilter { return v.Filters }).(GetMetalPlansFilterArrayOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o GetMetalPlansResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetMetalPlansResult) string { return v.Id }).(pulumi.StringOutput)
}

// The ID of the facility
func (o GetMetalPlansResultOutput) Plans() GetMetalPlansPlanArrayOutput {
	return o.ApplyT(func(v GetMetalPlansResult) []GetMetalPlansPlan { return v.Plans }).(GetMetalPlansPlanArrayOutput)
}

func (o GetMetalPlansResultOutput) Sorts() GetMetalPlansSortArrayOutput {
	return o.ApplyT(func(v GetMetalPlansResult) []GetMetalPlansSort { return v.Sorts }).(GetMetalPlansSortArrayOutput)
}

func init() {
	pulumi.RegisterOutputType(GetMetalPlansResultOutput{})
}
