// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package equinix

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Provides an Equinix Metal organization datasource.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
// 	"github.com/cuemby/pulumi-equinix/sdk/go/equinix"
// 	"github.com/pulumi/pulumi-equinix/sdk/go/equinix"
// 	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
// )
//
// func main() {
// 	pulumi.Run(func(ctx *pulumi.Context) error {
// 		test, err := equinix.GetMetalOrganization(ctx, &GetMetalOrganizationArgs{
// 			OrganizationId: pulumi.StringRef(local.Org_id),
// 		}, nil)
// 		if err != nil {
// 			return err
// 		}
// 		ctx.Export("projectsInTheOrg", test.ProjectIds)
// 		return nil
// 	})
// }
// ```
func LookupMetalOrganization(ctx *pulumi.Context, args *LookupMetalOrganizationArgs, opts ...pulumi.InvokeOption) (*LookupMetalOrganizationResult, error) {
	opts = pkgInvokeDefaultOpts(opts)
	var rv LookupMetalOrganizationResult
	err := ctx.Invoke("equinix:index/getMetalOrganization:GetMetalOrganization", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking GetMetalOrganization.
type LookupMetalOrganizationArgs struct {
	// Postal address.
	Addresses []GetMetalOrganizationAddress `pulumi:"addresses"`
	// The organization name.
	Name *string `pulumi:"name"`
	// The UUID of the organization resource.
	OrganizationId *string `pulumi:"organizationId"`
}

// A collection of values returned by GetMetalOrganization.
type LookupMetalOrganizationResult struct {
	// Postal address.
	Addresses []GetMetalOrganizationAddress `pulumi:"addresses"`
	// Description string.
	Description string `pulumi:"description"`
	// The provider-assigned unique ID for this managed resource.
	Id string `pulumi:"id"`
	// Logo URL.
	Logo           string `pulumi:"logo"`
	Name           string `pulumi:"name"`
	OrganizationId string `pulumi:"organizationId"`
	// UUIDs of project resources which belong to this organization.
	ProjectIds []string `pulumi:"projectIds"`
	// Twitter handle.
	Twitter string `pulumi:"twitter"`
	// Website link.
	Website string `pulumi:"website"`
}

func LookupMetalOrganizationOutput(ctx *pulumi.Context, args LookupMetalOrganizationOutputArgs, opts ...pulumi.InvokeOption) LookupMetalOrganizationResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (LookupMetalOrganizationResult, error) {
			args := v.(LookupMetalOrganizationArgs)
			r, err := LookupMetalOrganization(ctx, &args, opts...)
			var s LookupMetalOrganizationResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(LookupMetalOrganizationResultOutput)
}

// A collection of arguments for invoking GetMetalOrganization.
type LookupMetalOrganizationOutputArgs struct {
	// Postal address.
	Addresses GetMetalOrganizationAddressArrayInput `pulumi:"addresses"`
	// The organization name.
	Name pulumi.StringPtrInput `pulumi:"name"`
	// The UUID of the organization resource.
	OrganizationId pulumi.StringPtrInput `pulumi:"organizationId"`
}

func (LookupMetalOrganizationOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupMetalOrganizationArgs)(nil)).Elem()
}

// A collection of values returned by GetMetalOrganization.
type LookupMetalOrganizationResultOutput struct{ *pulumi.OutputState }

func (LookupMetalOrganizationResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupMetalOrganizationResult)(nil)).Elem()
}

func (o LookupMetalOrganizationResultOutput) ToLookupMetalOrganizationResultOutput() LookupMetalOrganizationResultOutput {
	return o
}

func (o LookupMetalOrganizationResultOutput) ToLookupMetalOrganizationResultOutputWithContext(ctx context.Context) LookupMetalOrganizationResultOutput {
	return o
}

// Postal address.
func (o LookupMetalOrganizationResultOutput) Addresses() GetMetalOrganizationAddressArrayOutput {
	return o.ApplyT(func(v LookupMetalOrganizationResult) []GetMetalOrganizationAddress { return v.Addresses }).(GetMetalOrganizationAddressArrayOutput)
}

// Description string.
func (o LookupMetalOrganizationResultOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v LookupMetalOrganizationResult) string { return v.Description }).(pulumi.StringOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o LookupMetalOrganizationResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupMetalOrganizationResult) string { return v.Id }).(pulumi.StringOutput)
}

// Logo URL.
func (o LookupMetalOrganizationResultOutput) Logo() pulumi.StringOutput {
	return o.ApplyT(func(v LookupMetalOrganizationResult) string { return v.Logo }).(pulumi.StringOutput)
}

func (o LookupMetalOrganizationResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupMetalOrganizationResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o LookupMetalOrganizationResultOutput) OrganizationId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupMetalOrganizationResult) string { return v.OrganizationId }).(pulumi.StringOutput)
}

// UUIDs of project resources which belong to this organization.
func (o LookupMetalOrganizationResultOutput) ProjectIds() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupMetalOrganizationResult) []string { return v.ProjectIds }).(pulumi.StringArrayOutput)
}

// Twitter handle.
func (o LookupMetalOrganizationResultOutput) Twitter() pulumi.StringOutput {
	return o.ApplyT(func(v LookupMetalOrganizationResult) string { return v.Twitter }).(pulumi.StringOutput)
}

// Website link.
func (o LookupMetalOrganizationResultOutput) Website() pulumi.StringOutput {
	return o.ApplyT(func(v LookupMetalOrganizationResult) string { return v.Website }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupMetalOrganizationResultOutput{})
}
