// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Cuemby.Equinix.Outputs
{

    [OutputType]
    public sealed class ECXL2ServiceprofileFeatures
    {
        /// <summary>
        /// Indicates whether or not connections to this profile
        /// can be created from remote metro locations.
        /// </summary>
        public readonly bool AllowRemoteConnections;
        /// <summary>
        /// Indicates whether or not this profile can be used for test
        /// connections.
        /// </summary>
        public readonly bool? TestProfile;

        [OutputConstructor]
        private ECXL2ServiceprofileFeatures(
            bool allowRemoteConnections,

            bool? testProfile)
        {
            AllowRemoteConnections = allowRemoteConnections;
            TestProfile = testProfile;
        }
    }
}
