// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Equinix.Outputs
{

    [OutputType]
    public sealed class ECXL2ConnectionSecondaryConnectionActionRequiredData
    {
        public readonly bool? Editable;
        public readonly string? Key;
        public readonly string? Label;
        public readonly string? ValidationPattern;
        /// <summary>
        /// additional information value
        /// </summary>
        public readonly string? Value;

        [OutputConstructor]
        private ECXL2ConnectionSecondaryConnectionActionRequiredData(
            bool? editable,

            string? key,

            string? label,

            string? validationPattern,

            string? value)
        {
            Editable = editable;
            Key = key;
            Label = label;
            ValidationPattern = validationPattern;
            Value = value;
        }
    }
}
