// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Equinix.Outputs
{

    [OutputType]
    public sealed class ECXL2ConnectionSecondaryConnectionAction
    {
        public readonly string? Message;
        public readonly string? OperationId;
        public readonly ImmutableArray<Outputs.ECXL2ConnectionSecondaryConnectionActionRequiredData> RequiredDatas;
        public readonly string? Type;

        [OutputConstructor]
        private ECXL2ConnectionSecondaryConnectionAction(
            string? message,

            string? operationId,

            ImmutableArray<Outputs.ECXL2ConnectionSecondaryConnectionActionRequiredData> requiredDatas,

            string? type)
        {
            Message = message;
            OperationId = operationId;
            RequiredDatas = requiredDatas;
            Type = type;
        }
    }
}
