// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Equinix.Outputs
{

    [OutputType]
    public sealed class ECXL2ServiceprofileSpeedBand
    {
        /// <summary>
        /// Speed/bandwidth supported by this service profile.
        /// </summary>
        public readonly int Speed;
        /// <summary>
        /// Unit of the speed/bandwidth supported by this service profile. One of
        /// `MB`, `GB`.
        /// </summary>
        public readonly string SpeedUnit;

        [OutputConstructor]
        private ECXL2ServiceprofileSpeedBand(
            int speed,

            string speedUnit)
        {
            Speed = speed;
            SpeedUnit = speedUnit;
        }
    }
}
