// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Equinix.Outputs
{

    [OutputType]
    public sealed class ECXL2ServiceprofilePort
    {
        /// <summary>
        /// The metro code of location where the port resides.
        /// </summary>
        public readonly string MetroCode;
        /// <summary>
        /// Unique identifier of the port.
        /// </summary>
        public readonly string Uuid;

        [OutputConstructor]
        private ECXL2ServiceprofilePort(
            string metroCode,

            string uuid)
        {
            MetroCode = metroCode;
            Uuid = uuid;
        }
    }
}
