// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Cuemby.Equinix.Outputs
{

    [OutputType]
    public sealed class GetECXL2SellerprofilesProfileMetroResult
    {
        public readonly string Code;
        public readonly ImmutableArray<string> Ibxes;
        public readonly string Name;
        public readonly ImmutableDictionary<string, string> Regions;

        [OutputConstructor]
        private GetECXL2SellerprofilesProfileMetroResult(
            string code,

            ImmutableArray<string> ibxes,

            string name,

            ImmutableDictionary<string, string> regions)
        {
            Code = code;
            Ibxes = ibxes;
            Name = name;
            Regions = regions;
        }
    }
}
