// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Cuemby.Equinix.Outputs
{

    [OutputType]
    public sealed class GetECXL2SellerprofilesProfileAdditionalInfoResult
    {
        public readonly bool CapturedInEmail;
        public readonly string DataType;
        public readonly string Description;
        public readonly bool Mandatory;
        public readonly string Name;

        [OutputConstructor]
        private GetECXL2SellerprofilesProfileAdditionalInfoResult(
            bool capturedInEmail,

            string dataType,

            string description,

            bool mandatory,

            string name)
        {
            CapturedInEmail = capturedInEmail;
            DataType = dataType;
            Description = description;
            Mandatory = mandatory;
            Name = name;
        }
    }
}
