// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Cuemby.Equinix.Outputs
{

    [OutputType]
    public sealed class NetworkDeviceClusterDetails
    {
        /// <summary>
        /// The ID of the cluster.
        /// </summary>
        public readonly string? ClusterId;
        /// <summary>
        /// The name of the cluster device
        /// </summary>
        public readonly string ClusterName;
        /// <summary>
        /// An object that has `node0` configuration.
        /// See Cluster Details - Nodes below for more details.
        /// </summary>
        public readonly Outputs.NetworkDeviceClusterDetailsNode0 Node0;
        /// <summary>
        /// An object that has `node1` configuration.
        /// See Cluster Details - Nodes below for more details.
        /// </summary>
        public readonly Outputs.NetworkDeviceClusterDetailsNode1 Node1;
        /// <summary>
        /// The number of nodes in the cluster.
        /// </summary>
        public readonly int? NumOfNodes;

        [OutputConstructor]
        private NetworkDeviceClusterDetails(
            string? clusterId,

            string clusterName,

            Outputs.NetworkDeviceClusterDetailsNode0 node0,

            Outputs.NetworkDeviceClusterDetailsNode1 node1,

            int? numOfNodes)
        {
            ClusterId = clusterId;
            ClusterName = clusterName;
            Node0 = node0;
            Node1 = node1;
            NumOfNodes = numOfNodes;
        }
    }
}
