// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "./types";
import * as utilities from "./utilities";

export function getMetalPlans(args?: GetMetalPlansArgs, opts?: pulumi.InvokeOptions): Promise<GetMetalPlansResult> {
    args = args || {};
    if (!opts) {
        opts = {}
    }

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
    return pulumi.runtime.invoke("equinix:index/getMetalPlans:GetMetalPlans", {
        "filters": args.filters,
        "sorts": args.sorts,
    }, opts);
}

/**
 * A collection of arguments for invoking GetMetalPlans.
 */
export interface GetMetalPlansArgs {
    /**
     * One or more attribute/values pairs to filter off of
     */
    filters?: inputs.GetMetalPlansFilter[];
    /**
     * One or more attribute/direction pairs on which to sort results. If multiple
     * sorts are provided, they will be applied in order
     */
    sorts?: inputs.GetMetalPlansSort[];
}

/**
 * A collection of values returned by GetMetalPlans.
 */
export interface GetMetalPlansResult {
    readonly filters?: outputs.GetMetalPlansFilter[];
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    /**
     * The ID of the facility
     */
    readonly plans: outputs.GetMetalPlansPlan[];
    readonly sorts?: outputs.GetMetalPlansSort[];
}

export function getMetalPlansOutput(args?: GetMetalPlansOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetMetalPlansResult> {
    return pulumi.output(args).apply(a => getMetalPlans(a, opts))
}

/**
 * A collection of arguments for invoking GetMetalPlans.
 */
export interface GetMetalPlansOutputArgs {
    /**
     * One or more attribute/values pairs to filter off of
     */
    filters?: pulumi.Input<pulumi.Input<inputs.GetMetalPlansFilterArgs>[]>;
    /**
     * One or more attribute/direction pairs on which to sort results. If multiple
     * sorts are provided, they will be applied in order
     */
    sorts?: pulumi.Input<pulumi.Input<inputs.GetMetalPlansSortArgs>[]>;
}
